# Generated by Django 4.1 on 2023-08-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellang', models.CharField(max_length=20)),
                ('selage', models.IntegerField()),
                ('seloc', models.CharField(max_length=50)),
                ('selltypes', models.CharField(choices=[('0', '--- Select your Preference ---'), ('1', 'Residential'), ('2', 'Commercial'), ('3', 'Agriculturial'), ('4', 'Industrial')], default='0', max_length=5)),
                ('sellinfo', models.CharField(max_length=200)),
                ('sellexpr', models.IntegerField()),
                ('sellcerti', models.FileField(upload_to='Certificates/')),
                ('sstatus', models.BooleanField(default=False)),
                ('sc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='byProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buylang', models.CharField(max_length=20)),
                ('buyage', models.IntegerField()),
                ('buyloc', models.CharField(max_length=50)),
                ('buytypes', models.CharField(choices=[('0', '--- Select your Preference ---'), ('1', 'Residential'), ('2', 'Commercial'), ('3', 'Agriculturial'), ('4', 'Industrial')], default='0', max_length=5)),
                ('buyinfo', models.CharField(max_length=200)),
                ('bstatus', models.BooleanField(default=False)),
                ('bc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
