# Generated by Django 4.1 on 2023-08-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0002_seprofile_byprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seprofile',
            name='sellcerti',
        ),
    ]
