# Generated by Django 4.1 on 2023-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0005_alter_seprofile_sellcerti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seprofile',
            name='sellcerti',
            field=models.FileField(default='pfle.png', upload_to='Attachments/'),
        ),
    ]
