# Generated by Django 4.1 on 2023-08-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0008_alter_seprofile_sellcerti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proptitle', models.CharField(max_length=200)),
                ('proptype', models.CharField(choices=[('s', 'Select your Property Type'), ('1', 'Residential'), ('2', 'Commercial'), ('3', 'Agricultural'), ('4', 'Industrial')], default='s', max_length=15)),
                ('propcity', models.CharField(max_length=200)),
                ('propstate', models.CharField(max_length=200)),
                ('propzipcode', models.CharField(max_length=20)),
                ('propdesc', models.TextField()),
                ('propsqft', models.PositiveIntegerField()),
                ('propprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_photo', models.ImageField(default='prop.png', upload_to='Prroperties/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('propstatus', models.CharField(choices=[('a', 'Available'), ('g', 'Sold')], default='a', max_length=10)),
                ('propdoc', models.FileField(upload_to='Attachments/')),
                ('propsoldto', models.CharField(max_length=200)),
                ('pown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
