# Generated by Django 4.1 on 2023-09-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0010_property_propown'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propprevown',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
