# Generated by Django 4.1 on 2023-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0013_alter_property_propprevown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propprevown',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
