# Generated by Django 4.1 on 2023-09-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0017_alter_property_propprevown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propprevown',
        ),
    ]
