# Generated by Django 4.1 on 2023-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RApp', '0019_property_propprevown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propsoldto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
